### ISSUE TITLE
structure of setting.py in docker installation

### ISSUE THREAD

**Issue by rahimramezanian** [SpiderClub/haipproxy#11]
What are the values of `SPLASH_URL` and `REDIS_HOST` when we install docker?

I used  `sudo docker-compose up` with default settings and I get errors

```
haipproxy_1  | 2018-03-08 12:40:38 [client] INFO: the updating task is starting...
haipproxy_1  | Traceback (most recent call last):
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 484, in connect
haipproxy_1  |     sock = self._connect()
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 541, in _connect
haipproxy_1  |     raise err
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 529, in _connect
haipproxy_1  |     sock.connect(socket_address)
haipproxy_1  | ConnectionRefusedError: [Errno 111] Connection refused
haipproxy_1  | 
haipproxy_1  | During handling of the above exception, another exception occurred:
haipproxy_1  | 
haipproxy_1  | Traceback (most recent call last):
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2879, in execute
haipproxy_1  |     return execute(conn, stack, raise_on_error)
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2810, in _execute_pipeline
haipproxy_1  |     connection.send_packed_command(all_cmds)
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 585, in send_packed_command
haipproxy_1  |     self.connect()
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 489, in connect
haipproxy_1  |     raise ConnectionError(self._error_message(e))
haipproxy_1  | redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
haipproxy_1  | 
haipproxy_1  | During handling of the above exception, another exception occurred:
haipproxy_1  | 
haipproxy_1  | Traceback (most recent call last):
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 484, in connect
haipproxy_1  |     sock = self._connect()
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 541, in _connect
haipproxy_1  |     raise err
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 529, in _connect
haipproxy_1  |     sock.connect(socket_address)
haipproxy_1  | ConnectionRefusedError: [Errno 111] Connection refused
haipproxy_1  | 
haipproxy_1  | During handling of the above exception, another exception occurred:
haipproxy_1  | 
haipproxy_1  | Traceback (most recent call last):
haipproxy_1  |   File "squid_update.py", line 19, in <module>
haipproxy_1  |     squid_conf_update()
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
haipproxy_1  |     return self.main(*args, **kwargs)
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
haipproxy_1  |     rv = self.invoke(ctx)
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
haipproxy_1  |     return ctx.invoke(self.callback, **ctx.params)
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
haipproxy_1  |     return callback(*args, **kwargs)
haipproxy_1  |   File "/haipproxy/scheduler/scheduler.py", line 234, in squid_conf_update
haipproxy_1  |     client.update_conf()
haipproxy_1  |   File "/haipproxy/client/squid.py", line 52, in update_conf
haipproxy_1  |     scored_proxies, ttl_proxies, speed_proxies = pipe.execute()
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2894, in execute
haipproxy_1  |     return execute(conn, stack, raise_on_error)
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2810, in _execute_pipeline
haipproxy_1  |     connection.send_packed_command(all_cmds)
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 585, in send_packed_command
haipproxy_1  |     self.connect()
haipproxy_1  |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 489, in connect
haipproxy_1  |     raise ConnectionError(self._error_message(e))
haipproxy_1  | redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
haipproxy_haipproxy_1 exited with code 1
```

**Comment by ResolveWang** [comment]
The `SPLASH_URL' is `'http://splash:8050'` and the `REDIS_HOST` is `'redis'` when using docker, just like this
```python 3
SPLASH_URL = 'http://splash:8050'
REDIS_HOST = 'redis'
```
If you come across any problem with `haipproxy`, please let me know
