### ISSUE TITLE
执行 python crawler_booter.py --usage crawler  出现语法错误

### ISSUE THREAD

**Issue by GangRock** [SpiderClub/haipproxy#57]
Hello，阿里云ECS上部署haipproxy，服务器端部署过程中，执行 “python crawler_booter.py --usage crawler” 还有其它三个命令出现以下错误：

Traceback (most recent call last):
  File "crawler_booter.py", line 19, in <module>
    from scheduler import crawler_start
  File "/var/www/myproxy/haipproxy-0.1/scheduler/__init__.py", line 5, in <module>
    from .scheduler import (
  File "/var/www/myproxy/haipproxy-0.1/scheduler/scheduler.py", line 21, in <module>
    from crawler.spiders import all_spiders
  File "/var/www/myproxy/haipproxy-0.1/crawler/spiders/__init__.py", line 45, in <module>
    from .common_spider import CommonSpider
  File "/var/www/myproxy/haipproxy-0.1/crawler/spiders/common_spider.py", line 6, in <module>
    from ..redis_spiders import RedisSpider
  File "/var/www/myproxy/haipproxy-0.1/crawler/redis_spiders.py", line 112
    yield from self.next_requests_process(self.task_queue)
             ^
SyntaxError: invalid syntax

谢谢！

**Comment by 3b295** [comment]
yield from 是python3.3引入的。检查一下你的python版本是不是不对。
