### ISSUE TITLE
安装 依赖发生错误

### ISSUE THREAD

**Issue by elwininc** [SpiderClub/haipproxy#61]
启动

python crawler_booter.py --usage crawler

没有找到模块
-----------------------------------------------
[root@squid haipproxy-0.1]# python crawler_booter.py --usage crawler
Traceback (most recent call last):
  File "crawler_booter.py", line 19, in <module>
    from scheduler import crawler_start
  File "/root/haipproxy-0.1/scheduler/__init__.py", line 5, in <module>
    from .scheduler import (
  File "/root/haipproxy-0.1/scheduler/scheduler.py", line 7, in <module>
    import click
ImportError: No module named 'click'
[root@squid haipproxy-0.1]#

**Comment by ResolveWang** [comment]
`pip install click` 试试

如果用的是docker compose,那么就在`requirements.txt`中添加一行内容`click==6.7`

**Comment by elwininc** [comment]
显示已经安装 程序找不到模块

[root@squid haipproxy-0.1]# pip install click
Requirement already satisfied: click in /usr/lib/python2.7/site-packages (6.7)
[root@squid haipproxy-0.1]# python crawler_booter.py --usage crawler
Traceback (most recent call last):
  File "crawler_booter.py", line 19, in <module>
    from scheduler import crawler_start
  File "/root/haipproxy-0.1/scheduler/__init__.py", line 5, in <module>
    from .scheduler import (
  File "/root/haipproxy-0.1/scheduler/scheduler.py", line 7, in <module>
    import click
ImportError: No module named 'click'
[root@squid haipproxy-0.1]#

**Comment by Ir1d** [comment]
`pip3 install click`
