### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by cxiaolng** [SpiderClub/haipproxy#66]
![image](https://user-images.githubusercontent.com/3888018/43653040-7f92bc90-9779-11e8-8a3d-c34ac0e5a150.png)

validator scheduler is starting...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/haipproxy/haipproxy/scheduler/scheduler.py", line 161, in schedule_task_with_lock
    release_lock(conn, task_name, lock_indentifier)
  File "/haipproxy/haipproxy/utils/redis_util.py", line 41, in release_lock
    identifier_origin = pipe.get(lock_name).decode()
AttributeError: 'NoneType' object has no attribute 'decode'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scheduler_booter.py", line 22, in <module>
    scheduler_start()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/haipproxy/haipproxy/scheduler/scheduler.py", line 197, in scheduler_start
    scheduler.schedule_all_right_now()
  File "/haipproxy/haipproxy/scheduler/scheduler.py", line 73, in schedule_all_right_now
    pool.map(self.schedule_task_with_lock, self.tasks)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by ResolveWang** [comment]
提供的信息不够全面，没法帮到你

**Comment by cxiaolng** [comment]
用的master分支，自定义了一个检校器，在CentOS 7上使用docker-compose up -d 运行一段时间就会报这个错

**Comment by cxiaolng** [comment]
对redis_util.py做了修改

def release_lock(conn, lock_name, identifier):
......
identifier_origin = pipe.get(lock_name).decode()
            if identifier_origin == identifier:

修改为
identifier_origin = pipe.get(lock_name)
            if identifier_origin is not None and identifier_origin.decode() == identifier:
