### ISSUE TITLE
启动调度器出现 TypeError: unsupported type for timedelta minutes component: NoneType

### ISSUE THREAD

**Issue by dta0502** [SpiderClub/haipproxy#75]
我在服务器部署过程中，进行到启动调度器这步：
python scheduler_booter.py --usage validator

就会出现如下错误：

Traceback (most recent call last):
  File "scheduler_booter.py", line 22, in <module>
    scheduler_start()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tding/haipproxy-0.1-v2/scheduler/scheduler.py", line 187, in scheduler_start
    scheduler.schedule_with_delay()
  File "/home/tding/haipproxy-0.1-v2/scheduler/scheduler.py", line 66, in schedule_with_delay
    schedule.every(internal).minutes.do(self.schedule_task_with_lock, task)
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 393, in do
    self._schedule_next_run()
  File "/usr/local/lib/python3.5/dist-packages/schedule/__init__.py", line 428, in _schedule_next_run
    self.period = datetime.timedelta(**{self.unit: interval})
TypeError: unsupported type for timedelta minutes component: NoneType

**Comment by ResolveWang** [comment]
python版本？
是否下载的是release中的？
